# miod runtime library

#APPNAME = 'miod_test'
#VERSION = '1.0'

top = '.'
#out = 'build_directory'

def configure(conf):
    conf.load('compiler_c')
    conf.env.CFLAGS = ['-g']
    
    pass

def build(bld):
    bld.stlib(source = 'miod_runtime/m_smartptr.c miod_runtime/m_class.c', target = 'miod_runtime')
    bld.program(source = 'src/main.c', includes = ['.'], target = 'miod_test', use = 'miod_runtime')
    pass

def options(opt):
    opt.load('compiler_c')
    pass
